### ISSUE TITLE
PHP CS Fixer: Configuration error of the application.

### ISSUE THREAD

**Issue by jbelien** [junstyle/vscode-php-cs-fixer#97]
I have some issue from time to time with this extension.

Looking at the console, I guess that `The path "/tmp/TableHandler.php" is not readable.` is the main issue.
I'm running this extension through [Remote - SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh).
It works usually fine so I guess it's not a configuration issue but as I said from time to time it fails.

Here is some console screenshots when the issue happens:

![image](https://user-images.githubusercontent.com/1150563/63348002-b011b680-c358-11e9-8982-9f5162c52ede.png)

![image](https://user-images.githubusercontent.com/1150563/63348032-c15ac300-c358-11e9-81a2-c5180d371a6a.png)

**Comment by jbelien** [comment]
I should add that the resulting file is quite messed up : some content is duplicated inside the file when it happens.
So maybe it's an issue from PHP CS Fixer itself ?

**Comment by junstyle** [comment]
![image](https://user-images.githubusercontent.com/3364972/63490901-6b1c8a00-c4e8-11e9-971a-602fc75c2298.png)

please check the permission of /tmp dir

**Comment by jbelien** [comment]
No issue with the permission on `/tmp` ; it is (still) the default permission : `drwxrwxrwt` (Debian)

**Comment by jimmy-jos** [comment]
I have the same issue on mac. @jbelien @junstyle did you happen to find a fix for this issue?

**Comment by boumanb** [comment]
Running into this now https://github.com/junstyle/vscode-php-cs-fixer/issues/153#issuecomment-2028610575

**Comment by boumanb** [comment]
I had to mount the tmp dir on the corresponding path

```json
{
    "php-cs-fixer.executablePath": "${workspaceFolder}/.vscode/php-cs-fixer",
    "php-cs-fixer.config": "${workspaceFolder}/.php-cs-fixer.php",
    "php-cs-fixer.tmpDir": "/tmp/php-cs-fixer",
}
```

Example docker file
```yaml
version: "3.5"
services:
  php-fpm:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-vite.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-vite.priority=3
      - traefik.http.routers.${WARDEN_ENV_NAME}-vite.rule=Host(`vite.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.${WARDEN_ENV_NAME}-vite.service=${WARDEN_ENV_NAME}-vite
      - traefik.http.services.${WARDEN_ENV_NAME}-vite.loadbalancer.server.port=5173
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
    volumes:
      - /tmp/php-cs-fixer:/tmp/php-cs-fixer
```
